import React, { memo } from 'react';
import Head from 'next/head';
import Menu from '../Menu/Menu';

interface ILayout {
  children: JSX.Element;
}

const Layout: React.FC<ILayout> = (props: React.PropsWithChildren<ILayout>) => {
  const { children } = props;

  const menu = [
    { path: '/', label: 'Home' },
    { path: '/translations', label: 'Translations' },
  ];

  return (
    <>
      <Head>
        <title>Translations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <Menu menu={menu} />
      <main>{children}</main>
    </>
  );
};

export default memo(Layout);
